name: Test & Deploy #Название pipeline который будет выполнять github actions

on:
  push:
    branches:
      - staging # указываем название ветки в которую хотим пушить и запускать наш деплой

jobs:
  tests:
    name: Tests # название конктретной работы в pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  # клонируем репозиторый
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn # устанавливаем зависимости

      - name: Test
        run: yarn test # запускаем скрипт тестами

  deploy:
    name: Deploy
    needs: tests # указываем зависимую джобу т/е в данном случае деплой не запустится если тесты завершились ошибкой
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1 # This is the action
        with:
          args: "deploy"
        env:
          FLY_API_TOKEN: ${{ secrets.INCTAGRAM_TRAINEE_FRONT_TOKEN }}

#  INCTAGRAM_TRAINEE_FRONT_TOKEN